### ISSUE TITLE
Support for Fiat Payment Gateways and Other Tokens

### ISSUE THREAD

**Issue by layinka** [GMX9/Crypto-Exchange-PHP#3]
Hi,
Great work on this, its a very laudable and needed effort.

Is there anyway to add other tokens for examples, Tokens issued on the Waves Blockchain or or the Stellar blockchain ,for example?

Also, How do i add some other payment gateways(Paypal, paystack etc) to allow people exchange fiat for crypto or vice versa?

BR

**Comment by GMX9** [comment]
Hello, this crypto exchange was built using an API from a third party provider, from which you can create there your own account, unfortunally at it's current state it's not possible to exchange fiat for tokens or to implement more tokens than the avaliable at their website.
You can check the avaliable coins at changenow.io and simply add them at the coins text file.
