### ISSUE TITLE
no modules folder found in zip file

### ISSUE THREAD

**Issue by rhivent** [GMX9/Crypto-Exchange-PHP#5]
require_once(): Failed opening required 'localhost/php_cryptomodules/index/controller/index.php' (include_path='.:/usr/share/php') in /var/www/html/Crypto-Exchange-PHP/lib/controllers.php on line 57

**Comment by GMX9** [comment]
Is the project at your root folders?

**Comment by GMX9** [comment]
Ive noticed there was missing the modules folder in repo, added now
