### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by walterc73** [GMX9/Crypto-Exchange-PHP#7]
I'm trying to install and where can I get the api key for installation.

**Comment by GMX9** [comment]
You can get an API from the official website of changeNOW:
https://changenow.io/for-partners

**Comment by walterc73** [comment]
Thanks, when I go to index.php 
went out below message, 

Carregando...

Warning: include(configs/global.php): failed to open stream: No such file or directory in /var/www/html/wal-eX/includes/frontend/navbar.php on line 3

Warning: include(): Failed opening 'configs/global.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/wal-eX/includes/frontend/navbar.php on line 3

Notice: Undefined variable: config in /var/www/html/wal-eX/includes/frontend/navbar.php on line 10

Fatal error: Uncaught Error: Call to a member function real_escape_string() on null in /var/www/html/wal-eX/modules/index/view/index.tpl.php:58 Stack trace: #0 /var/www/html/wal-eX/lib/controllers.php(59): include() #1 /var/www/html/wal-eX/modules/index/controller/index.php(19): controllers->display('modules/index/v...') #2 /var/www/html/wal-eX/lib/controllers.php(52): defaultpage->index() #3 /var/www/html/wal-eX/index.php(44): controllers->pageIndex('page') #4 {main} thrown in /var/www/html/wal-eX/modules/index/view/index.tpl.php on line 58

Would you pls advise.
thank you
